name: Configuration Update Base
type: module
description: 'Provides basic revert and update functionality for other modules'
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - drupal:config
