_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 0d1ff9c4-d84d-4a68-a5b6-0d1c1c8c72dc
name: NeuroNet
mail: neuronet.glia@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
